"""origin index

Revision ID: 98e0b1f95dbc
Revises: 5de914e66a8e
Create Date: 2025-03-17 10:59:09.983521

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "98e0b1f95dbc"
down_revision: Union[str, None] = "5de914e66a8e"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(
        "origin_type_and_name_idx",
        "imports",
        ["origin_type_name", "origin_name"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("origin_type_and_name_idx", table_name="imports")
    # ### end Alembic commands ###
